2017/04/24 12:04:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create_user".' in G:\wamp2\www\test\framework\web\CController.php:486
Stack trace:
#0 G:\wamp2\www\test\framework\web\CController.php(270): CController->missingAction('create_user')
#1 G:\wamp2\www\test\framework\web\CWebApplication.php(282): CController->run('create_user')
#2 G:\wamp2\www\test\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create_user')
#3 G:\wamp2\www\test\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 G:\wamp2\www\test\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/test/api/user_login
---
2017/04/24 12:07:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create_user".' in G:\wamp2\www\test\framework\web\CController.php:486
Stack trace:
#0 G:\wamp2\www\test\framework\web\CController.php(270): CController->missingAction('create_user')
#1 G:\wamp2\www\test\framework\web\CWebApplication.php(282): CController->run('create_user')
#2 G:\wamp2\www\test\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create_user')
#3 G:\wamp2\www\test\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 G:\wamp2\www\test\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/test/api/user_login
---
2017/04/24 12:07:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create_user".' in G:\wamp2\www\test\framework\web\CController.php:486
Stack trace:
#0 G:\wamp2\www\test\framework\web\CController.php(270): CController->missingAction('create_user')
#1 G:\wamp2\www\test\framework\web\CWebApplication.php(282): CController->run('create_user')
#2 G:\wamp2\www\test\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create_user')
#3 G:\wamp2\www\test\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 G:\wamp2\www\test\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/test/api/user_login
---
2017/04/24 12:21:07 [error] [exception.CDbException] exception 'CDbException' with message 'Table "user" does not have a column named "username".' in G:\wamp2\www\test\framework\db\schema\CDbCommandBuilder.php:697
Stack trace:
#0 G:\wamp2\www\test\framework\db\ar\CActiveRecord.php(1526): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 G:\wamp2\www\test\protected\controllers\ApiController.php(43): CActiveRecord->findByAttributes(Array)
#2 G:\wamp2\www\test\framework\web\actions\CInlineAction.php(49): ApiController->actionUser_login()
#3 G:\wamp2\www\test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 G:\wamp2\www\test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 G:\wamp2\www\test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 G:\wamp2\www\test\framework\web\CWebApplication.php(282): CController->run('user_login')
#7 G:\wamp2\www\test\framework\web\CWebApplication.php(141): CWebApplication->runController('api/user_login')
#8 G:\wamp2\www\test\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 G:\wamp2\www\test\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/test/api/user_login?key=f25a2fc72690b780b2a14e140ef6a9e0&username=123&password=1
---
2017/04/24 12:23:15 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'application' in 'where clause'. The SQL statement executed was: SELECT * FROM `user` `t` WHERE `t`.`user_name`=:yp0 AND `t`.`password`=:yp1 AND (application/json) LIMIT 1. Bound with :yp0='123', :yp1='c4ca4238a0b923820dcc509a6f75849b'.
in G:\wamp2\www\test\protected\controllers\ApiController.php (43)
in G:\wamp2\www\test\index.php (13)
2017/04/24 12:23:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'application' in 'where clause'. The SQL statement executed was: SELECT * FROM `user` `t` WHERE `t`.`user_name`=:yp0 AND `t`.`password`=:yp1 AND (application/json) LIMIT 1. Bound with :yp0='123', :yp1='c4ca4238a0b923820dcc509a6f75849b'' in G:\wamp2\www\test\framework\db\CDbCommand.php:543
Stack trace:
#0 G:\wamp2\www\test\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 G:\wamp2\www\test\framework\db\ar\CActiveRecord.php(1359): CDbCommand->queryRow()
#2 G:\wamp2\www\test\framework\db\ar\CActiveRecord.php(1527): CActiveRecord->query(Object(CDbCriteria))
#3 G:\wamp2\www\test\protected\controllers\ApiController.php(43): CActiveRecord->findByAttributes(Array, 'application/jso...')
#4 G:\wamp2\www\test\framework\web\actions\CInlineAction.php(49): ApiController->actionUser_login()
#5 G:\wamp2\www\test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 G:\wamp2\www\test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 G:\wamp2\www\test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 G:\wamp2\www\test\framework\web\CWebApplication.php(282): CController->run('user_login')
#9 G:\wamp2\www\test\framework\web\CWebApplication.php(141): CWebApplication->runController('api/user_login')
#10 G:\wamp2\www\test\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 G:\wamp2\www\test\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/test/api/user_login?key=f25a2fc72690b780b2a14e140ef6a9e0&username=123&password=1
---
2017/04/24 13:12:34 [error] [exception.CDbException] exception 'CDbException' with message 'Table "user" does not have a column named "username".' in G:\wamp2\www\test\framework\db\schema\CDbCommandBuilder.php:697
Stack trace:
#0 G:\wamp2\www\test\framework\db\ar\CActiveRecord.php(1526): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 G:\wamp2\www\test\protected\controllers\ApiController.php(115): CActiveRecord->findByAttributes(Array)
#2 G:\wamp2\www\test\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate_user()
#3 G:\wamp2\www\test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 G:\wamp2\www\test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 G:\wamp2\www\test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 G:\wamp2\www\test\framework\web\CWebApplication.php(282): CController->run('create_user')
#7 G:\wamp2\www\test\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create_user')
#8 G:\wamp2\www\test\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 G:\wamp2\www\test\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/test/api/create_user/
---
2017/04/24 13:13:13 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:13:25 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:13:40 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:13:46 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:14:44 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:14:54 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:14:56 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:14:56 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:14:57 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:15:07 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:15:21 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:15:41 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:15:44 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:15:45 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:15:46 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:16:37 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:16:42 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:17:07 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 13:17:24 [warning] [application] Failed to set unsafe attribute "key" of "User".
in G:\wamp2\www\test\protected\controllers\ApiController.php (113)
in G:\wamp2\www\test\index.php (13)
2017/04/24 18:22:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in E:\xampp\htdocs\YiiRestfulAPI\framework\web\CController.php:486
Stack trace:
#0 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CController.php(270): CController->missingAction('')
#1 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php(282): CController->run('')
#2 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php(141): CWebApplication->runController('api')
#3 E:\xampp\htdocs\YiiRestfulAPI\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 E:\xampp\htdocs\YiiRestfulAPI\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/YiiRestfulAPI/api
---
2017/04/24 19:00:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "create_user".' in E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php(141): CWebApplication->runController('create_user')
#1 E:\xampp\htdocs\YiiRestfulAPI\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\YiiRestfulAPI\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/YiiRestfulAPI/create_user?user_name=atul&password=test123&status=1&first_name=Atul&last_name=Tagra
---
2017/04/24 19:01:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "create_user".' in E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php(141): CWebApplication->runController('create_user')
#1 E:\xampp\htdocs\YiiRestfulAPI\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\YiiRestfulAPI\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/YiiRestfulAPI/create_user?user_name=atul&password=test123&status=1&first_name=Atul&last_name=Tagra&key=f25a2fc72690b780b2a14e140ef6a9e0
---
2017/04/24 19:08:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'yii_api'' in E:\xampp\htdocs\YiiRestfulAPI\framework\db\CDbConnection.php:399
Stack trace:
#0 E:\xampp\htdocs\YiiRestfulAPI\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 E:\xampp\htdocs\YiiRestfulAPI\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 E:\xampp\htdocs\YiiRestfulAPI\framework\base\CModule.php(394): CDbConnection->init()
#3 E:\xampp\htdocs\YiiRestfulAPI\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 E:\xampp\htdocs\YiiRestfulAPI\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 E:\xampp\htdocs\YiiRestfulAPI\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 E:\xampp\htdocs\YiiRestfulAPI\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(User))
#7 E:\xampp\htdocs\YiiRestfulAPI\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 E:\xampp\htdocs\YiiRestfulAPI\protected\controllers\ApiController.php(112): CActiveRecord->__construct()
#9 E:\xampp\htdocs\YiiRestfulAPI\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate_user()
#10 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php(282): CController->run('create_user')
#14 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create_user')
#15 E:\xampp\htdocs\YiiRestfulAPI\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 E:\xampp\htdocs\YiiRestfulAPI\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/YiiRestfulAPI/api/create_user?key=f25a2fc72690b780b2a14e140ef6a9e0&user_name=atul&password=test123&first_name=Atul&last_name=Tagra&status=1
---
2017/04/24 19:11:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'yii_api'' in E:\xampp\htdocs\YiiRestfulAPI\framework\db\CDbConnection.php:399
Stack trace:
#0 E:\xampp\htdocs\YiiRestfulAPI\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 E:\xampp\htdocs\YiiRestfulAPI\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 E:\xampp\htdocs\YiiRestfulAPI\framework\base\CModule.php(394): CDbConnection->init()
#3 E:\xampp\htdocs\YiiRestfulAPI\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 E:\xampp\htdocs\YiiRestfulAPI\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 E:\xampp\htdocs\YiiRestfulAPI\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 E:\xampp\htdocs\YiiRestfulAPI\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(User))
#7 E:\xampp\htdocs\YiiRestfulAPI\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 E:\xampp\htdocs\YiiRestfulAPI\protected\controllers\ApiController.php(113): CActiveRecord->__construct()
#9 E:\xampp\htdocs\YiiRestfulAPI\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate_user()
#10 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php(282): CController->run('create_user')
#14 E:\xampp\htdocs\YiiRestfulAPI\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create_user')
#15 E:\xampp\htdocs\YiiRestfulAPI\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 E:\xampp\htdocs\YiiRestfulAPI\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/YiiRestfulAPI/api/create_user?key=f25a2fc72690b780b2a14e140ef6a9e0&user_name=atul&password=test123&first_name=Atul&last_name=Tagra&status=1
---
2017/04/24 19:13:40 [warning] [application] Failed to set unsafe attribute "key" of "User".
in E:\xampp\htdocs\YiiRestfulAPI\protected\controllers\ApiController.php (114)
in E:\xampp\htdocs\YiiRestfulAPI\index.php (13)
2017/04/24 19:16:02 [warning] [application] Failed to set unsafe attribute "key" of "User".
in E:\xampp\htdocs\YiiRestfulAPI\protected\controllers\ApiController.php (113)
in E:\xampp\htdocs\YiiRestfulAPI\index.php (13)
2017/04/24 20:16:26 [warning] [application] Failed to set unsafe attribute "key" of "User".
in E:\xampp\htdocs\YiiRestfulAPI\protected\controllers\ApiController.php (113)
in E:\xampp\htdocs\YiiRestfulAPI\index.php (13)
2017/04/24 20:18:25 [warning] [application] Failed to set unsafe attribute "key" of "User".
in E:\xampp\htdocs\YiiRestfulAPI\protected\controllers\ApiController.php (113)
in E:\xampp\htdocs\YiiRestfulAPI\index.php (13)
2017/04/24 14:22:09 [warning] [application] Failed to set unsafe attribute "key" of "User".
in E:\xampp\htdocs\YiiRestfulAPI\protected\controllers\ApiController.php (113)
in E:\xampp\htdocs\YiiRestfulAPI\index.php (13)
